apiVersion: v1
kind: Service
metadata:
  name: wil-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil-app
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 8888
